src/crappy/camera/xiapi.py
The acquisition of the images first needed to be stopped before switching trigger mode
=> [fix] Bug when switching trigger mode

crappy/blocks/grapher.py
single line change to grapher.py - prevents collisions between plot elements when plots are made very thin
=> added additional layout cmd to properly layout arbitrary aspect ratio plots

crappy/blocks/grapher.py
Since clear button was problematic to click and interfered with the layout etc., I suggest removing the button but keeping the same functionality through a keypress option (user presses 'c' to clear plot).
=> remove clear button and replace with 'c' keypress

docs/source/developers.rst, src/crappy/blocks/meta_block/block.py
With this PR the Block object is now reset (by means of the `Block.reset()` method) at the end of each call to `Block._cleanup()`.
It cleans up all the references to the instantiated Blocks, as well as the synchronization objects and other instantiated multiprocessing objects. 
These references and objects are anyway not of any use at that point anymore.
Users now don't need to manually call `crappy.reset()` before being able to restart a script.
=> Reset Block after cleanup

src/crappy/tool/camera_config/camera_config.py
Currently, the user has to click on the Apply Settings button to update the settings in the configuration window.
This is not very convenient.
In this PR, an Auto apply button is added (903caae8). When checked, the user can change the settings of the camera in real time.
When checked, the Apply Settings button  is disabled (45886a8a).
By default, the Auto apply button is disabled, because it can create bugs with some cameras.
=> Add button to auto apply settings in the configuration window

docs/source/crappy_docs/tools.rst, src/crappy/blocks/camera.py, src/crappy/blocks/camera_processes/camera_process.py, src/crappy/blocks/camera_processes/dic_ve.py, src/crappy/blocks/camera_processes/dis_correl.py, src/crappy/blocks/camera_processes/display.py, src/crappy/blocks/camera_processes/gpu_ve.py, src/crappy/blocks/camera_processes/video_extenso.py, src/crappy/blocks/gpu_correl.py, src/crappy/tool/camera_config/__init__.py, src/crappy/tool/camera_config/config_tools/__init__.py, src/crappy/tool/camera_config/config_tools/box.py, src/crappy/tool/camera_config/config_tools/overlay_object.py
Until now, there was no possibility for users to add a custom overlay on top of the images displayed by a [Camera Displayer](https://github.com/LaboratoireMecaniqueLille/crappy/blob/8c49d4e12ccbcfab47eb8809744afaf55ab8e122/src/crappy/blocks/camera_processes/display.py) window.
Users could only add one or several bounding boxes as an overlay, using the [Box](https://github.com/LaboratoireMecaniqueLille/crappy/blob/8c49d4e12ccbcfab47eb8809744afaf55ab8e122/src/crappy/tool/camera_config/config_tools/box.py) object.
It was brought to our attention in #47 that this possibility could be of interest for users.
Consequently, an `Overlay` object was created (571711fe) as a base class for overlays. It possesses a `draw` method, that draws a shape on top of the displayed image.
The `Displayer` object …
=> Allow custom overlay on Camera Displayer

docs/source/crappy_docs/blocks.rst, src/crappy/blocks/camera.py, src/crappy/blocks/camera_processes/camera_process.py, src/crappy/blocks/camera_processes/dic_ve.py, src/crappy/blocks/camera_processes/dis_correl.py, src/crappy/blocks/camera_processes/display.py, src/crappy/blocks/camera_processes/gpu_correl.py, src/crappy/blocks/camera_processes/gpu_ve.py, src/crappy/blocks/camera_processes/record.py, src/crappy/blocks/camera_processes/video_extenso.py, src/crappy/blocks/dic_ve.py, src/crappy/blocks/dis_correl.py, src/crappy/blocks/gpu_correl.py, src/crappy/blocks/gpu_ve.py, src/crappy/blocks/video_extenso.py
Until now, few efforts were made to allow users to create their own children of `Camera` Blocks (and of `CameraProcess` as well).
A first step towards more accessibility was made with #49, but it was only improving the display of overlays on top of the displayed images for a custom `Camera` Block.
The instantiation of the Block itself was still chaotic, as it required to access private members of the class and to manage obscure arguments (see the last comment of #47).
With this PR, the creation of custom `Camera` Blocks and `CameraProcess` is made more accessible and straightforward :
- The name of the methods of `CameraProcess` meant to be overridden or called by users were switched from private to public (a2721f4f, 2ba09588).
- Same goes for the attributes of `CameraProcess` (14119ff5) …
=> Make it more user-friendly to instantiate custom Camera Blocks

src/crappy/camera/fake_camera.py, src/crappy/camera/meta_camera/camera.py, src/crappy/camera/meta_camera/camera_setting/camera_scale_setting.py, src/crappy/tool/camera_config/camera_config.py
Currently, there is no step value for the variation of the camera scale setting values when the user uses the slide bar in the configuration window. The value of the step is fixed, depending on the type of the boundaries.
This is not very convenient because a step value can be given for some camera parameters.
In this PR, a step attribute is added when the camera scale setting is created (5b21ffb9).
=> Add a step option for the camera scale setting in the configuration window

docs/source/tutorials/complex_custom_objects.rst, examples/custom_objects/custom_camera_block.py
The possibility for users to create their own children of the Camera Block was added in #50.
However, there was no script in the examples folder demonstrating this feature.
This PR simply adds such a script, that contains the same code as used in the tutorials but annotated with comments and docstrings.
=> Add example demonstrating the creation of a custom Camera Block

docs/source/downloads/complex_custom_objects/custom_path.py, docs/source/tutorials/complex_custom_objects.rst, examples/blocks/generator/generator_feedback_loop.py, examples/custom_objects/custom_generator_path.py, src/crappy/blocks/generator.py, src/crappy/blocks/generator_path/conditional.py, src/crappy/blocks/generator_path/constant.py, src/crappy/blocks/generator_path/custom.py, src/crappy/blocks/generator_path/cyclic.py, src/crappy/blocks/generator_path/cyclic_ramp.py, src/crappy/blocks/generator_path/integrator.py, src/crappy/blocks/generator_path/meta_path/path.py, src/crappy/blocks/generator_path/ramp.py, src/crappy/blocks/generator_path/sine.py
Until now in Crappy, the base `Path` object was requiring the last sent command and its timestamp as arguments.
Any other `Path` subclassing it also needed to take these two values as arguments, and to pass them to the parent class (for example with `super().__init__(last_time, last_cmd)`).
Starting with version `2.0.0`, users can now define their own custom `Path` objects.
With the old architecture, however, they had to define a `_last_cmd` and a `_last_time` argument to their new class, only to provide it as argument to the parent class. 
This is at the same time not elegant, a potential source of bugs, and definitely not intuitive.
Instead, this PR slightly modifies the base `Path` object and the `Generator` Block so that the last command and its timestamp are not needed as arguments …
=> Simplify the creation of custom Path objects

README.md, docs/README.md, examples/README.md, setup.py, src/README.md, tests/README.md, util/README.md
The README file of the repo hasn't been updated for a while.
It was missing a badge indicating the supported Python versions.
The main README was updated in 1e3e3604.
README files for all the folders at the root of the repo were also created in 91469607, to make it clearer what each directory is intended for.
The README file is also now used as the long description in `setup.py`, instead of `what_is_crappy.rst` (42148afd).
=> Update the README files

src/crappy/actuator/__init__.py, src/crappy/actuator/_deprecated.py, src/crappy/blocks/__init__.py, src/crappy/blocks/_deprecated.py, src/crappy/blocks/camera.py, src/crappy/blocks/ioblock.py, src/crappy/blocks/machine.py, src/crappy/camera/__init__.py, src/crappy/camera/_deprecated.py, src/crappy/inout/__init__.py, src/crappy/inout/_deprecated.py
With the upcoming change of major version to 2.0.0, a number of public classes in the project will be renamed.
In order to provide support for users migrating from version 1.5 to 2.0, the deprecated names of the renamed objects are now nicely handled instead of raising bare Exceptions.
This PR closes #60.
Two different strategies were used.
For Blocks that are directly instantiated by users, empty Blocks with the deprecated names and simply raising an Exception were created (5bf52172). The Exception is raised at `__init__`, before Crappy even starts.
For Camera, InOut and Actuator objects for which the user only provides a name, the Camera, IOBlock and Machine Blocks check if the given name is deprecated (respectively 8a57fb4d, 1d346ea1 and 4e3d4954). If so, an Exception is raised, again …
=> Add deprecation errors for objects renamed between v1.5 and v2.0

src/crappy/camera/gstreamer_camera_basic.py, src/crappy/camera/gstreamer_camera_v4l2.py
Currently, there is no format detection in the camera gstreamer basic and formats are guessed. The user can then just choose the image format among a non exhaustive list, even if some more are available. 
This is not optimal for the user.
In this PR, the available formats are detected by using the Gst device monitor (032f79f). Then, the list of the available formats is inspected in order to check if those formats are applicable (9daf836).
Closes #58.
=> Enhancement of the format detection in camera gstreamer basic

CODEOWNERS, src/crappy/camera/_v4l2_base.py, src/crappy/camera/gstreamer_camera_v4l2.py, src/crappy/camera/opencv_camera_v4l2.py
In #76, a few improvements were brought to the [`gstreamer_camera_basic.py`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/430b0ed8416e152089b1ccb456709c260ce58d5f/src/crappy/camera/gstreamer_camera_basic.py) file. The branch on which these changes were brought was however not up to date with `develop`, and the improvements could not be propagated as is to other camera files.
With this PR, the changes in `gstreamer_camera_basic.py` are propagated to [`gstreamer_camera_v4l2.py`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/430b0ed8416e152089b1ccb456709c260ce58d5f/src/crappy/camera/gstreamer_camera_v4l2.py), and similar style corrections and minor fixes are also brought to [`opencv_camera_v4l2.py`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/430b0ed8416e15 …
=> Various style refactorings and fixes on `CameraGstreamer` and `CameraOpencv` objects

src/crappy/camera/meta_camera/camera_setting/camera_scale_setting.py, src/crappy/camera/ximea_xiapi.py
As detailed in #16, there is currently room for improvement for the [`XiAPI` Camera](https://github.com/LaboratoireMecaniqueLille/crappy/blob/ecd7d70b81ca0b345d33a2d0fe5153386819875a/src/crappy/camera/ximea_xiapi.py) object. Although it is heavily used at the LaMcube laboratory, not all the available settings are implemented in Crappy, and the behavior is quite buggy when trying to tune the implemented ones. The `timeout` argument of the image acquisition is also not implemented, although this feature has been requested for long.
With this PR, most of the available settings for Ximea cameras are now implemented. The accessible settings vary according to the model of the driven camera, and the entire class is now much more stable. A new `timeout` argument was added to manage the …
=> Improvement of the XiAPI camera

.github/workflows/python_package.yml
In an effort to detect bugs in the code as early as possible, this PR adds a GitHub workflow to the project. This workflow installs Crappy, and checks that it imports as expected. The checks are performed on Linux, macOS and Windows, on all the Python versions supported by Crappy. It runs whenever a Pull Request is opened or modified on the `main` or `develop` branch, and on each first day of the month.
This workflow is a first step towards a more extensive test suite for Crappy, to be integrated at a later point (#57). It is a step towards completion of #63.
=> Add workflow for checking the installation and import of Crappy

docs/source/conf.py, pyproject.toml, src/crappy/__init__.py, src/crappy/__version__.py, src/crappy/_global.py, src/crappy/blocks/camera_processes/record.py, src/crappy/inout/daqmx.py
The release 2.0.3 is a bug fix release that addresses several minor problems:
* The `cv2` backend for the [`ImageSaver`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/b276d7833a94733526ee1431e29805cb9bdf7190/src/crappy/blocks/camera_processes/record.py) object was relegated from second to third choice as it is much slower than the `pil` and `sitk` backends (07accf35).
* Two minor bugs were making the [`DAQmx`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/b276d7833a94733526ee1431e29805cb9bdf7190/src/crappy/inout/daqmx.py) InOut impossible to use (41c911c8 and b696b1ae).
* Some attributes of numpy were used in the top-level [`__init__.py`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/b276d7833a94733526ee1431e29805cb9bdf7190/src/crappy/__init__.py) and …
=> Release of version 2.0.3

src/crappy/actuator/phidgets_stepper4a.py
Currently, limit switches are not implemented for the Phidget4AStepper. It is a problem because limit switches are an important safety feature on a tensile test machine.
Also, the motor position is always driven and calculated from its current position. It can be problematic in some situations, and taking a fix absolute position as a reference might be needed.
In this PR, limit switches are implemented (228d347) and can now stop the motor when hit. An absolute mode is also added (3052e75) with the possibility to save the last position of the motor (e32147f) in order to, for example, use it later as a reference position.
=> Add new options on Phidget4AStepper

src/crappy/actuator/phidgets_stepper4a.py
Currently, the state of the switches are always checked in the `open` method of the Phidget4AStepper to keep the motor to move if a switch has been disconnected or hit. Nevertheless, it could be useful to pass this check if you know already know the a switch has been hit and you want to drive the motor away from the switch.
That's why in this PR, a class attribute has been implemented (6beedcc) in order to choose if you want to perform this check or not.
=> Add a class attribute to check switches state in the open method

docs/source/conf.py, pyproject.toml, src/crappy/__version__.py
The new 2.0.4 release brings various minor improvements to Crappy:
* It adds the [`Phidget4AStepper`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/b7daa6ba3ef80527b75b6b604ece1802cb1d25b7/src/crappy/actuator/phidgets_stepper4a.py) Actuator, for controlling  a Phidget stepper motor driver (#88)
* It adds the [`PhidgetWheatstoneBridge`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/b7daa6ba3ef80527b75b6b604ece1802cb1d25b7/src/crappy/inout/phidgets_wheatstone_bridge.py) InOut, for driving a Phidget load cell conditioner (#88)
* It adds an automated [GitHub workflow](https://github.com/LaboratoireMecaniqueLille/crappy/blob/b7daa6ba3ef80527b75b6b604ece1802cb1d25b7/.github/workflows/python_package.yml) checking that Crappy builds and installs on the supported OS and …
=> build: update project version from 2.0.3 to 2.0.4

src/crappy/__init__.py
In versions `2.0.3` and `2.0.4`, the [`resources`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/be9ce7a89cb9f471367e1a98acdb9caf837d8ac8/src/crappy/_global.py#L96) class was moved to the [`_global.py`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/be9ce7a89cb9f471367e1a98acdb9caf837d8ac8/src/crappy/_global.py#L96) file (12ee73a081ce643cef0560b6159b18c3b2e18fd6). However, there was an omission to import this class in the [`__init__.py`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/be9ce7a89cb9f471367e1a98acdb9caf837d8ac8/src/crappy/__init__.py) file. Consequently, all the examples relying on the `resources` class (mostly the ones handling example images) were broken.
This PR simply adds back the correct import in `__init__.py`, therefore fixing the broken …
=> Missing `resources` class in `__init__.py`

src/crappy/tool/camera_config/camera_config.py
When using the Camera Configuration window ([`CameraConfig`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/f7ceb73e95cc42737005649b843c01a9859873d3/src/crappy/tool/camera_config/camera_config.py#L29)), the shape and data type of the last acquired image is saved. It is then passed to the parent [`Camera` Block](https://github.com/LaboratoireMecaniqueLille/crappy/blob/f7ceb73e95cc42737005649b843c01a9859873d3/src/crappy/blocks/camera.py#L21), for initializing internal data structures. When no image can be grabbed, an information image is displayed in the configuration window. However, until now, the shape and dtype of this information image was being saved and passed to the `Camera` Block. This was causing cryptic bugs for users.
With this PR, the shape and dtype is never saved …
=> Not setting shape and dtype in config window when no image acquired

src/crappy/blocks/camera.py, src/crappy/blocks/camera_processes/camera_process.py, src/crappy/tool/camera_config/camera_config.py
In the [`Camera` Block](https://github.com/LaboratoireMecaniqueLille/crappy/blob/f7ceb73e95cc42737005649b843c01a9859873d3/src/crappy/blocks/camera.py#L21) and [`CameraProcess` class](https://github.com/LaboratoireMecaniqueLille/crappy/blob/f7ceb73e95cc42737005649b843c01a9859873d3/src/crappy/blocks/camera_processes/camera_process.py#L23), the `img_shape` argument was type-hinted as `Tuple[int, int]`. This was correct for gray level images, but incorrect for color images.
With this PR, the type hints are updated to `Union[Tuple[int, int], Tuple[int, int, int]]` to also consider the image colors.
=> Wrong type hint for the image shape argument

src/crappy/blocks/camera_processes/record.py
As reported in #98, the name of the images saved by the [`Camera` Block](https://github.com/LaboratoireMecaniqueLille/crappy/blob/f7ceb73e95cc42737005649b843c01a9859873d3/src/crappy/blocks/camera.py#L21) (via the [`ImageSaver` `CameraProcess`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/f7ceb73e95cc42737005649b843c01a9859873d3/src/crappy/blocks/camera_processes/record.py#L32)) is currently in the format `f'{index}_{time:.3f}.{ext}'`. Example image names: `1_0.100`, `2_0.200`, `21_2.100`, etc. This poses problems for navigating in file explorers, or for compatibility with third -party processing software, as the first character in the name is used for sorting.
This PR changes the name of the recorded images to `f'{index:06d}_{time:.3f}.{ext}'`, therefore adding a zero-padding …
=> Change name of images recorded by the `Camera` Block

docs/source/features.rst, examples/blocks/camera/camera_record_send_msg.py, src/crappy/blocks/camera.py, src/crappy/blocks/camera_processes/record.py
Since Crappy `2.0.0`, the [`Camera` Block](https://github.com/LaboratoireMecaniqueLille/crappy/blob/16340f945f867bf38e30efe67965f77aba490a48/src/crappy/blocks/camera.py#L21) never outputs messages to downstream Blocks. That is because the acquisition, display, and recording of the images are all managed from within the `Camera` Block. However, as pointed out in #98, there is currently no way for other Blocks to know when an image is saved. This feature could be useful when performing image analysis in post-processing, in case actions need to be performed during the test, to synchronize with the timestamps of the saved images.
With this PR, the `Camera` Block now sends messages containing the timestamp and metadata of each recorded image. It does so in case all these conditions are true:
* …
=> Send signal when recording images with Camera Block

src/crappy/blocks/camera.py, src/crappy/blocks/camera_processes/record.py
Since #107, the [`Camera` Block](https://github.com/LaboratoireMecaniqueLille/crappy/blob/595df27ec58fcb138124062c5050c7e42178e7ba/src/crappy/blocks/camera.py#L21) sends a signal to downstream Blocks when recording images in case no image processing is performed and output Links are present. Originally, the sent message was containing only the timestamp of the saved image and its metadata. However, these two labels did not allow integration with the [`Synchronizer` Block](https://github.com/LaboratoireMecaniqueLille/crappy/blob/595df27ec58fcb138124062c5050c7e42178e7ba/src/crappy/blocks/synchronizer.py#L11) added in #108, as the time label is a special one and the metadata label cannot be interpolated.
To solve this issue, this PR adds a new label `'index'`, carrying the image index, to …
=> Send image index on save

src/crappy/tool/camera_config/camera_config.py, src/crappy/tool/camera_config/camera_config_boxes.py, src/crappy/tool/camera_config/dic_ve_config.py, src/crappy/tool/camera_config/dis_correl_config.py, src/crappy/tool/camera_config/video_extenso_config.py
As detailed in #113, the camera configuration window currently displays repeatedly an error image in case the Camera object returning the images alternatively returns images or `None`. This behavior is not the intended one, as the error image should only be displayed once as the very first frame. In case `None` values are received later, the last acquired image should remain in the interface. 
This PR fixes #113. It also removes duplicate code in children of the camera configuration window class, by using ad-hoc helper functions re-defined by the children classes. As a side-effect, this refactoring propagates the fix of d6247ef0 to the children classes. Its propagation had been omitted, due to duplicates in code !
=> Fix camera configuration bug and remove duplicate code

src/crappy/blocks/camera_processes/record.py
As detailed in #124, two out of the four backends were buggy when recording color images, namely Pillow and SimpleITK.
This PR addresses these two bugs using simple image operations and overlooked function call arguments.
Fixes #124
=> Fix color image recording

src/crappy/blocks/camera.py, src/crappy/blocks/dic_ve.py, src/crappy/blocks/dis_correl.py, src/crappy/blocks/gpu_correl.py, src/crappy/blocks/gpu_ve.py, src/crappy/blocks/video_extenso.py, src/crappy/lamcube/bispectral.py
Changes the order of backends listed for recording images, and adds a forgotten warning.
=> Minor updates in camera documentation

src/crappy/blocks/camera_processes/display.py, src/crappy/blocks/camera_processes/gpu_correl.py, src/crappy/blocks/fake_machine.py, src/crappy/blocks/mean.py, src/crappy/camera/seek_thermal_pro.py, src/crappy/modifier/demux.py, src/crappy/modifier/mean.py, src/crappy/modifier/median.py, src/crappy/modifier/moving_avg.py, src/crappy/modifier/moving_med.py, src/crappy/tool/camera_config/camera_config.py, src/crappy/tool/image_processing/dic_ve.py, src/crappy/tool/image_processing/dis_correl.py, src/crappy/tool/image_processing/video_extenso/video_extenso.py
As detailed in #125, starting from version 2.0.0, some numpy operations no longer return Python types and return numpy types instead. This is particularly bothersome when using `isinstance()` for example, or operations like `np.max(img) + 1` that would previously return up to 256 on uint8 images and would now return 0 instead of 256.
A quick and easy fix was simply to cast numpy operations that now return numpy types into `float` or `int`, so that the behavior is preserved compared to numpy<2.0.0. 
closes #125
=> fix: cast numpy types to Python types wherever needed

.github/workflows/test_python_package.yml, README.md, docs/source/installation.rst, pyproject.toml
The supported versions of Crappy haven't been updated for a while. In a separate branch, features of Python 3.8 and 3.9 are being added to the code base. This PR simply updates the lower and higher supported Python versions wherever needed. Related to #63.
=> Add support for Python 3.13

docs/source/crappy_docs/blocks.rst, docs/source/developers.rst, docs/source/features.rst, docs/source/tutorials/custom_objects.rst, examples/blocks/pause_block.py, src/crappy/blocks/__init__.py, src/crappy/blocks/meta_block/block.py, src/crappy/blocks/pause.py, src/crappy/blocks/sink.py, src/crappy/blocks/stop_block.py, src/crappy/blocks/stop_button.py
As requested in #127, this PR adds a new pause feature to Crappy. This feature can be useful in situations when a running test needs to be temporarily suspended, for example for safely manipulating on the setup. 
The base Block was modified so that the `main()` method does not call `loop()` when the Block is paused. 
Also, a new `Pause` Block was added, to trigger a pause or resume a test based on a user defined set of conditions.
Finally, documentation was added about the new feature and Block.
closes #127
=> Add a pause mechanism for the Blocks
